//auth
export const AUTHENTICATE = "AUTHENTICATE";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_START = "AUTH_START";
export const AUTH_SUCCESS = "AUTH_SUCCESS";
export const AUTH_FAIL = "AUTH_FAIL";
export const AUTH_TOKEN_CONFIRM_CODE = "AUTH_TOKEN_CONFIRM_CODE";
export const AUTH_TOKEN_RESET_PASSWORD = "AUTH_TOKEN_RESET_PASSWORD";
export const AUTH_PASSWORD_RESETED = "AUTH_PASSWORD_RESETED";
export const END_OF_REQUEST = "END_OF_REQUEST";
export const REQUEST_FAILD = "REQUEST_FAILD";
export const EMPTY_TOKENS = "EMPTY_TOKENS";
export const RESULT_REQUEST = "RESULT_REQUEST";
export const AUTH_FORM_ERRORS = "AUTH_FORM_ERRORS";
export const END_START_UP = "END_START_UP";
//sechudles
export const VIEW_SECHUDLE = "VIEW_SECHUDLE";
export const SINGLE_SECHUDLE = "SINGLE_SECHUDLE";
export const ADD_SECHUDLE = "ADD_SECHUDLE";
export const UPDATE_SECHUDLE = "UPDATE_SECHUDLE";
export const UPDATE_ISDONE_SECHUDLE = "UPDATE_ISDONE_SECHUDLE";
export const DELETE_SECHUDLE = "DELETE_SECHUDLE";
export const GET_ALL_SECHUDLE = "GET_ALL_SECHUDLE";
export const EMPTY_SINGLE_SCHEDULE = "EMPTY_SINGLE_SCHEDULE";
export const EMPTY_VIEW_SCHEDULE = "EMPTY_VIEW_SCHEDULE";
export const START_LOAD_SCHEDULE = "START_LOAD_SCHEDULE";
export const START_LOAD_EDIT_SCHEDULE = "START_LOAD_EDIT_SCHEDULE";
export const FINISHED_LOAD_SCHEDULE = "FINISHED_LOAD_SCHEDULE";
export const FINISHED_LOAD_EDIT_SCHEDULE = "FINISHED_LOAD_EDIT_SCHEDULE";
export const EDIT_SCHEDULE = "EDIT_SCHEDULE";
export const SET_MESSAGE_SCHEDULE = "SET_MESSAGE_SCHEDULE";
//
export const EMPTY_MESSAGE="EMPTY_MESSAGE";
